'use strict';
window.YKimport(function(lib,game,ui,get,ai,_status){
	lib.help['云空·挑战']='双方各选择至多5名角色入场，通过变换位置，使用技能和普通攻击击败敌方获得胜利（目前该模式仍在制作中，敬请期待！）';
	lib.init.req("https://raw.githubusercontent.com/qxqdpcq/yunkong/main/extension/challengeContent.js",function(){
		eval(this.responseText);
	},function(e){
	},true);
	game.addMode('ykChallenge',{
		start:function(){
			lib.init.req("https://raw.githubusercontent.com/qxqdpcq/yunkong/main/extension/challengeContent.js",function(){
				eval(this.responseText);
			},function(e){
			},true);
		},
	},{
		translate:'云空·挑战',
		extension:'云空',
		config:{
		},
	});
});
